import type { CommunityPostItem } from "@/types/communityDTO";

export const mockPosts: CommunityPostItem[] = [
  {
    id: 1,
    title: "유치원 선생님들의 일상 공유",
    content:
      "오늘은 아이들과 함께 미술 활동을 했어요. 아이들이 너무 즐거워했네요!",
    category: "TEACHER",
    categoryName: "일상",
    categoryDescription: "일상적인 이야기를 나누는 공간입니다",
    likeCount: 15,
    commentCount: 8,
    viewCount: 120,
    userNickname: "선생님1",
    userRole: "TEACHER",
    career: "3",
    createdAt: "2024-05-04T10:00:00.000Z",
    updatedAt: "2024-05-04T10:00:00.000Z",
  },
  {
    id: 2,
    title: "유치원 운영 팁 공유",
    content: "새로운 학기 시작에 앞서 준비해야 할 것들에 대해 공유해보아요.",
    category: "TEACHER",
    categoryName: "운영",
    categoryDescription: "유치원 운영에 관한 정보를 공유하는 공간입니다",
    likeCount: 23,
    commentCount: 12,
    viewCount: 156,
    userNickname: "선생님2",
    userRole: "TEACHER",
    career: "5",
    createdAt: "2024-05-03T15:30:00.000Z",
    updatedAt: "2024-05-03T15:30:00.000Z",
  },
  {
    id: 3,
    title: "교육 자료 공유합니다",
    content: "만들어본 교육 자료를 공유해요. 도움이 되셨으면 좋겠습니다.",
    category: "TEACHER",
    categoryName: "교육",
    categoryDescription: "교육 자료와 방법을 공유하는 공간입니다",
    likeCount: 18,
    commentCount: 5,
    viewCount: 98,
    userNickname: "선생님3",
    userRole: "TEACHER",
    career: "2",
    createdAt: "2024-05-02T09:15:00.000Z",
    updatedAt: "2024-05-02T09:15:00.000Z",
  },
];
