export const URL_PATHS = {
  TEST: "test",
  HOME: "/",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SCHOOL: "/school",
  SCHOOL_DETAIL: "/school/:id",
  REVIEW: "/school/:id/review",
  REVIEW_WORK: "/school/:id/review-work",
  REVIEW_LEARNING: "/school/:id/review-learning",
  REVIEW_EDITOR: "/school/:id/review/new",
  COMMUNITY: "/community",
  COMMUNITY_TEACHER: "/community-teacher",
  COMMUNITY_STUDENT: "/community-pre-teacher",
  COMMUNITY_POST: "/community/:id",
  COMMUNITY_POST_EDITOR: "/community/new",
  BOOKMARKS: "/bookmarks",
  USER: "/user",
  USER_PROFILE_EDITOR: "/user/profile",
  USER_NICKNAME_EDITOR: "/user/profile/nickname",
  USER_PASSWORD_EDITOR: "/user/account-setting/password",
  USER_ACCOUNT_SETTING: "/user/account-setting",
  PERMISSION_TEST: "/permission-test",
};
