export const URL_PATHS = {
  TEST: "test",
  ROOT: "/",
  // 홈
  HOME: "/home",
  SHORTCUTS_EDITOR: "/home/shortcuts",
  // 로그인 및 회원가입
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  // 기관
  SCHOOL: "/school",
  SCHOOL_DETAIL: "/school/:id",
  // 리뷰
  REVIEW: "/school/:id/review",
  REVIEW_WORK: "/school/:id/review-work",
  REVIEW_LEARNING: "/school/:id/review-learning",
  REVIEW_EDITOR: "/school/:id/review/new",
  // 커뮤니티
  COMMUNITY: "/community",
  COMMUNITY_TEACHER: "/community-teacher",
  COMMUNITY_STUDENT: "/community-pre-teacher",
  COMMUNITY_POST: "/community/:id",
  COMMUNITY_POST_EDITOR: "/community/new",
  BOOKMARKS: "/bookmarks",
  // 프로필
  USER: "/user",
  USER_POST: "/user/my-post",
  USER_PROFILE_EDITOR: "/user/profile",
  USER_NICKNAME_EDITOR: "/user/profile/nickname",
  USER_PASSWORD_EDITOR: "/user/account-setting/password",
  USER_ACCOUNT_SETTING: "/user/account-setting",
  NOTICE: "/user/notice",
  NOTICE_DETAIL: "/user/notice/:id",
  INQUIRY: "/user/inquiry",
  INQUIRY_PUBLIC: "/user/inquiry/public",
  INQUIRY_MY: "/user/inquiry/my",
  INQUIRY_EDITOR: "/user/inquiry/new",
  // 테스트
  PERMISSION_TEST: "/permission-test",
};
