export const URL = {
  TEST: "test",
  HOME: "/",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SCHOOL: "/school",
  SCHOOL_DETAIL: "/school/:id",
  SCHOOL_REVIEW: "/school/:id/review",
  SCHOOL_REVIEW_EDITOR: "/school/:id/review/new",
  COMMUNITY: "/community",
  COMMUNITY_TEACHER: "/community-teacher",
  COMMUNITY_STUDENT: "/community-pre-teacher",
  COMMUNITY_POST: "/community/:id",
  COMMUNITY_POST_EDITOR: "/community/new",
  BOOKMARKS: "/bookmarks",
  USER: "/user",
};
